[package]
name = "croncat-sdk-tasks"
version = "1.0.0"
authors = { workspace = true }
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"
license = { workspace = true }
description = "CronCat tasks package containing CosmWasm types and messages"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw20 = { workspace = true }
cron_schedule = { workspace = true }

croncat-mod-generic = { workspace = true, features = ["library"]}
croncat-sdk-core = { workspace = true }
mod-sdk = { workspace = true }

sha2 = { workspace = true }
hex = { workspace = true }
