[package]
name = "croncat-sdk-agents"
version = "1.0.0"
authors = { workspace = true }
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"
license = { workspace = true }
description = "CronCat agents package containing CosmWasm types, messages, and errors."

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true }
croncat-sdk-core = { workspace = true }