[package]
name = "croncat-sdk-manager"
version = "1.0.0"
authors = { workspace = true }
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"
license = { workspace = true }
description = "CronCat Manager types, messages, and errors."

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
thiserror = { workspace = true }
cw20 = { workspace = true }
cw-storage-plus = { workspace = true}
croncat-sdk-core = { workspace = true }
croncat-sdk-tasks = { workspace = true }