[package]
name = "cw-croncat-core"
description = "CronCat core logic allowing automated scheduling of transactions and IFTTT for the interchain"
license = "MIT OR Apache-2.0"
version = "0.1.5"
edition = "2021"

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.5
"""

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["staking", "stargate"] }
cw-rules-core = { version = "0.1.2", path = "../cw-rules-core" }
generic-query = { version = "0.1.1", path = "../generic-query" }
cw-storage-plus = "0.16.0"
cron_schedule = "0.2.3"
cw2 = "0.16.0"
cw20 = { version = "0.13.4" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
hex = "0.4"
sha2 = "0.10.6"
serde-cw-value = "0.7.0"
# TODO: update when this feature is merged
serde-json-wasm = { version = "0.4.1", git = "https://github.com/CyberHoward/serde-json-wasm", rev = "cdc78130b25d65981b74a5e4a10a9f8667292d36" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
cw-multi-test = { version = "0.16.0", features = ["staking"] }
cw20-base = { version = "0.13.4", features = ["library"] }
rusty-hook = "0.11.2"