[package]
name = "cw-croncat-core"
description = "CronCat core logic allowing automated scheduling of transactions and IFTTT for the interchain"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.5
"""

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["staking", "stargate"] }
cw-rules-core = { version = "*", path = "../cw-rules-core"}
cosmwasm-storage = { version = "1.0.0" }
cw-storage-plus = "0.13"
cron_schedule = "0.2.2"
cw2 = "0.13"
cw20 = { version = "0.13" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
hex = "0.4"
sha2 = "0.9"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
cw-multi-test = { version = "0.13", features = ["staking"] }
cw20-base = { version = "0.13", features = ["library"] }
serde-json-wasm = "0.4.1"
