[package]
name = "mod-sdk"
version = "0.1.3"
authors = []
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"
license = { workspace = true }
description = "Contains basic types and errors useful for CronCat modules"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
thiserror = { workspace = true }
