name: Gas Benchmark

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  gas:
    name: Calculate gas costs in local juno
    runs-on: ubuntu-latest
    env:
      GAS_OUT_DIR: gas_reports
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.64.0
          target: wasm32-unknown-unknown
          override: true

      - name: Rust Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
          key: ${{ runner.os }}-cargo-with-artifacts-${{ hashFiles('**/Cargo.lock') }}

      - name: Set latest just version
        run: echo "JUST_VERSION=$(cargo search just -q | sed -n -e '/^just[[:space:]]/p' | cut -d '"' -f 2)" >> $GITHUB_ENV

      - name: Get cached just
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/just
          key: ${{ runner.os }}-just-${{ env.JUST_VERSION }}

      - name: Install just
        run: cargo install just || true

      - name: Run Gas Benchmarks
        run: just gas-benchmark

      - name: Raw Gas Report
        run: cat gas_reports/gas_report.json

      - name: Post gas diff to PR
        uses: de-husk/cosm-orc-gas-diff-action@v0.6.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          current_json: "./gas_reports/gas_report.json"